paths:              # main work spaces (intermediate results saved here)
  ALILENS: /sharefs/alicpt/users/chenwz/Testarea/FORECAST/A_NEW_WORK_MUST/rec/A_lenrec_internal/ALILENS


qe:                 # reconstruction estimators (e.g., 'ptt', 'ptt_bh', 'p_p', 'p', etc.)
  lib_qe_keys:
    - 'p'

map:                # map parameters
  nside: 2048
  dlmax: 5000


noise:              # nrms map and fwhm
  nlev:
    - /sharefs/alicpt/users/chenwz/Testarea/FORECAST/A_NEW_WORK_MUST/rec/prepare/Ali_normalized_const_red_nrms_map.fits
  fwhm_f:
    - 0

mask:               # masks, I recommend both 'bb' and 'apodiz' to be the apodized mask to fasten the CG convergence
  bb: /sharefs/alicpt/users/chenwz/Testarea/FORECAST/A_NEW_WORK_MUST/mask/AliCPT_20uKcut150_C_2048_sm01.fits
  apodiz: /sharefs/alicpt/users/chenwz/Testarea/FORECAST/A_NEW_WORK_MUST/mask/AliCPT_20uKcut150_C_2048_sm01.fits

simulation:
  seeds: 301        # All the simulation seeds
  bias: 300         # # how many sets of CMB maps used to calculate mean field, must be even number
  var: 0            # how many sets of CMB maps used to calculate covariance matrix
  nset: 20          # the number of group 
  nwidth: 15        # the width of each group (how many sets in each group) #Notice：shuffle is performed inside each group, make j=i+1 & cyclically，see 'ss_dict' in 'params.py'
# Rules: (1) nset * nwidth = bias + var (2) nwidth <= bias/2 & nwidth <= var, ensure each group has enough sims for mf and cov calculation

observation:      # observation map paths 
  cmbs:
    - /sharefs/alicpt/users/chenwz/Testarea/FORECAST/A_NEW_WORK_MUST/ilc/output_ali/clean/HILC0_TQU_clean_map_%05d.fits


reconstruction:   # Parameters for lenrec
  lmin_ivf: 200
  lmax_ivf: 5200
  lmax_qlm: 5000
  nsims : 300
  nsims_from_seeds: true


rec_path:           # Reconstruction save path
  qlm_rec:
    /sharefs/alicpt/users/chenwz/Testarea/FORECAST/A_NEW_WORK_MUST/rec/A_lenrec_internal/qlm_rec
